export const cardPaths = {
    gaming: {
        front: "/assets/imgs/game-page/theme/gaming/cards/front/front.svg",
        backs: [
            "/assets/imgs/game-page/theme/gaming/cards/back/ace-of-diamonds.svg",
            "/assets/imgs/game-page/theme/gaming/cards/back/banana.svg",
            "/assets/imgs/game-page/theme/gaming/cards/back/creeper.svg",
            "/assets/imgs/game-page/theme/gaming/cards/back/dice.svg",
            "/assets/imgs/game-page/theme/gaming/cards/back/game-controller.svg",
            "/assets/imgs/game-page/theme/gaming/cards/back/gameboy.svg",
            "/assets/imgs/game-page/theme/gaming/cards/back/level-up.svg",
            "/assets/imgs/game-page/theme/gaming/cards/back/maze.svg",
            "/assets/imgs/game-page/theme/gaming/cards/back/mushroom.svg",
            "/assets/imgs/game-page/theme/gaming/cards/back/pacman-ghost.svg",
            "/assets/imgs/game-page/theme/gaming/cards/back/pacman.svg",
            "/assets/imgs/game-page/theme/gaming/cards/back/pawn.svg",
            "/assets/imgs/game-page/theme/gaming/cards/back/play.svg",
            "/assets/imgs/game-page/theme/gaming/cards/back/puzzle.svg",
            "/assets/imgs/game-page/theme/gaming/cards/back/snake.svg",
            "/assets/imgs/game-page/theme/gaming/cards/back/square.svg",
            "/assets/imgs/game-page/theme/gaming/cards/back/star.svg",
            "/assets/imgs/game-page/theme/gaming/cards/back/triangle.svg",
        ],
    },
    codeVibes: {
        front: "/assets/imgs/game-page/theme/code-vibes/cards/front/front.svg",
        backs: [
            "/assets/imgs/game-page/theme/code-vibes/cards/back/angular.svg",
            "/assets/imgs/game-page/theme/code-vibes/cards/back/bootstrap.svg",
            "/assets/imgs/game-page/theme/code-vibes/cards/back/css.svg",
            "/assets/imgs/game-page/theme/code-vibes/cards/back/django.svg",
            "/assets/imgs/game-page/theme/code-vibes/cards/back/docker.svg",
            "/assets/imgs/game-page/theme/code-vibes/cards/back/firebase.svg",
            "/assets/imgs/game-page/theme/code-vibes/cards/back/git.svg",
            "/assets/imgs/game-page/theme/code-vibes/cards/back/github.svg",
            "/assets/imgs/game-page/theme/code-vibes/cards/back/html.svg",
            "/assets/imgs/game-page/theme/code-vibes/cards/back/javascript.svg",
            "/assets/imgs/game-page/theme/code-vibes/cards/back/nodejs.svg",
            "/assets/imgs/game-page/theme/code-vibes/cards/back/postgresql.svg",
            "/assets/imgs/game-page/theme/code-vibes/cards/back/python.svg",
            "/assets/imgs/game-page/theme/code-vibes/cards/back/react.svg",
            "/assets/imgs/game-page/theme/code-vibes/cards/back/sass.svg",
            "/assets/imgs/game-page/theme/code-vibes/cards/back/terminal.svg",
            "/assets/imgs/game-page/theme/code-vibes/cards/back/typescript.svg",
            "/assets/imgs/game-page/theme/code-vibes/cards/back/vue.svg",
        ],
    },
};
